# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Specify we are using the latest NODE JS orb
orbs:
  node: circleci/node@5.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # Hello-World Job
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # Build and test the client dev and prod and src code
  build-and-test-client:
    # Set execution environment to latest node JS version
    executor: node/default
    steps:
      # Checkout the code as the first step
      - checkout

      # Set NPM as the Node package manager
      - node/install-packages:
        pkg-manager: "npm"
      
      # Install dependencies
      - run: npm install

      # Run Unit Tests on Client src
      - run: 
          name: Test Client Src
          command: npm run test -- --selectProjects client

      # Build Dev Client
      - run:
          name: Build Dev Client
          command: |
            npm run buildDev

      # Run our tests
      - run: 
          name: Test Dev Client
          command: |
            npm run test -- --selectProjects build

      # Build Prod Client
      - run:
          name: Build Prod Client
          command: |
            npm run buildProd

      # Run our test
      - run: 
          name: Test Prod Client
          command: |
            npm run test -- --selectProjects build

  # Build and test the server
  build-and-test-server:
    # Set execution environment to latest node JS version
    executor: node/default
    steps:
      # Checkout the code as the first step
      - checkout

      # Set NPM as the Node package manager
      - node/install-packages:
        pkg-manager: "npm"
      
      # Install dependencies
      - run: npm install

      # Run server unit tests
      - run: npm run test -- --selectProjects server


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  # Run the hello world job
  say-hello-workflow:
    jobs:
      - say-hello

  build-and-test-workflow:
    jobs:
      - build-and-test-client
      - build-and-test-server